version: 2.1

orbs:
  node: circleci/node@4.5.1

jobs:
  lint-and-test:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

  build:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages
      - run:
          name: Build
          command: yarn build

workflows:
  run_ci:
    jobs:
      - lint-and-test
      - build:
          requires:
            - lint-and-test
