version: 2.1

orbs:
  node: circleci/node@4.5.1
  gh: circleci/github-cli@1.0.3
jobs:
  lint-and-test:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

  build:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages
      - run:
          name: Build
          command: npm run build

    create_release:
      steps:
        - checkout
        - run:
            name: Set env vars
            command: |
              echo 'export APP_VERSION=grep '"version"' package.json | cut -d '"' -f 4 | head -n 1' >> $BASH_ENV
        - run:
            name: show war
            command: |
              source $BASH_ENV


workflows:
  run_ci:
    jobs:
      - lint-and-test
      - build:
          requires:
            - lint-and-test
