version: 2.1

orbs:
  node: circleci/node@4.5.1
  gh: circleci/github-cli@1.0.3
jobs:
  lint-and-test:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages:
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

  build:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages:
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build

  create_release:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - run:
            name: Set env vars
            command: gh release create
            environment:
              APP_VERSION: grep '"version"' package.json | cut -d '"' -f 4 | head -n 1'
        
      - run:
          name: show war
          command: |
            source APP_VERSION


workflows:
  run_ci:
    jobs:
       - node/test
       - gh/release:
          context:
            - GITHUB_CREDS
          filters:
            branches:
              only:
                - main
          notes-file: changelog.md
          requires:
            - node/test
          tag: 1.0.0
          title: The initial release
      # - lint-and-test
      # - build:
      #     requires:
      #       - lint-and-test