version: 2.1

orbs:
  node: circleci/node@4.5.1
  github-release: unmadeworks/github-release@1.4.0
jobs:
  lint-and-test:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages:
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test

  build:
    docker:
      - image: 'cimg/base:stable'
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: 14.15.1
          npm-version: 7.12.0
      - node/install-packages:
          override-ci-command: yarn install --frozen-lockfile
      - run:
          name: Build
          command: yarn build    
          
  create_release:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - github-release/github-release:
          REPO_NAME: vl-tuning-new
      


workflows:
  run_ci:
    jobs:
      - create_release
      # - node/test
      
      # - lint-and-test
      # - build:
      #     requires:
      #       - lint-and-test