import Head from 'next/head';
import {VFC} from 'react';
import {getDataFromTree} from '@apollo/client/react/ssr';

import {withApollo} from 'src/apollo/withApollo';
// Import {useProductsNamesQuery} from 'src/apollo/types';

const Home: VFC = () =>
// Const {data} = useProductsNamesQuery();

	 (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				{/* <h1>{JSON.stringify(data)}</h1> */}
				<h2>Hello2</h2>
			</main>
		</>
	);
export default withApollo(Home, {getDataFromTree});
