import Head from 'next/head';
import Hello from 'components/hello';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hello />
			<main>
				<h1>Hello</h1>
			</main>
		</>
	);
}
