import Head from 'next/head';
import {useQuery} from '@apollo/client';
import {VFC} from 'react';

import {withApollo} from 'src/apollo/withApollo';
import {PRODUCTS_NAMES_QUERY} from 'queries/products';

const Home: VFC = () => {
	const {data} = useQuery(PRODUCTS_NAMES_QUERY);
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<h1>{JSON.stringify(data)}</h1>
				<h2>Hello2</h2>
			</main>
		</>
	);
};

export default withApollo(Home);
